name: Build PHP 7.0

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ${{ matrix.os }} 
#    services: 
#      mysql-db:
#        image: mysql:5.7
#        env:
#          MYSQL_ROOT_PASSWORD: 123456
#          MYSQL_DATABASE: testing_db
#        ports:
#          - 3306:3306
#        options: >-
#          --health-cmd="mysqladmin ping"
#          --health-interval=10s
#          --health-timeout=5s
#          --health-retries=3
    strategy: 
      fail-fast: true
      matrix: 
        os: [ ubuntu-latest ]
        php: [7.0]
            
    name: PHP ${{matrix.php}} on ${{matrix.os}}
    
    steps:
      
      - name: Clone Repo
        uses: actions/checkout@v1
      
      - name: Start MySQL
        run: |
          sudo systemctl start mysql.service
          while ! mysqladmin ping --host=127.0.0.1 --password=123456 --silent; do
            sleep 1
          done
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }} 
          extensions: mysqli, mbstring, sqlsrv
          tools: phpunit:5.7.27, composer
          
      #- name: List Containers IPs
      #  run: docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)
        
      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction --no-dev
        
      - name: Create DIR
        run: mkdir -m777 -p /home/runner/work/framework/framework/app/sto/sessions
        
      - name: LS
        run: ls /etc/mysql
      
      - name: Change MySQL Auth Method
        run: mysql -uroot -proot -e "ALTER USER root@localhost IDENTIFIED WITH mysql_native_password BY 'root';"
        
      - name: Show MySQL Config
        run: mysql -uroot -proot -e "show variables"
    
      - name: Execute Tests
        run: phpunit -v
      
      
        
