name: Build PHP 7.0

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ${{ matrix.os }} 
    strategy: 
      fail-fast: true
      matrix: 
        os: [ ubuntu-latest ]
        php: [7.0]
            
    name: PHP ${{matrix.php}} on ${{matrix.os}}
    
    steps:
      
      - name: Clone Repo
        uses: actions/checkout@v1
        
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build
      
      - name: Start MySQL
        run: |
          echo "Start MySQL"
          sudo systemctl start mysql.service
          echo "Waiting to start MySQL"
          while ! mysqladmin ping --host=127.0.0.1 --password=123456 --silent; do
            sleep 1
          done
          
          echo "Done"
          mysql -uroot -proot -e "select * from mysql.user;"
          
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }} 
          extensions: mysqli, mbstring, sqlsrv
          tools: phpunit:5.7.27, composer
          
      #- name: List Containers IPs
      #  run: docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)
        
      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction --no-dev
        
      - name: Create DIR
        run: mkdir -m777 -p /home/runner/work/framework/framework/app/sto/sessions
          
      
        
      - name: Show MySQL Config
        run: mysql -uroot -proot -e "show variables"
    
      - name: Execute Tests
        run: phpunit -v
      
      
        
